In [1]:
import pandas as pd
df=pd.read_csv('Downloads/Data/salaries.csv')
df.describe()

       Unnamed: 0    work_year        salary  salary_in_usd  remote_ratio
count  607.000000   607.000000  6.070000e+02     607.000000     607.00000
mean   303.000000  2021.405272  3.240001e+05  112297.869852      70.92257
std    175.370085     0.692133  1.544357e+06   70957.259411      40.70913
min      0.000000  2020.000000  4.000000e+03    2859.000000       0.00000
25%    151.500000  2021.000000  7.000000e+04   62726.000000      50.00000
50%    303.000000  2022.000000  1.150000e+05  101570.000000     100.00000
75%    454.500000  2022.000000  1.650000e+05  150000.000000     100.00000
max    606.000000  2022.000000  3.040000e+07  600000.000000     100.00000

In [3]:
df2=pd.read_csv('Downloads/Data/salaries2.csv')
df2.describe()

       Unnamed: 0    work_year  salary_in_usd
count  607.000000   606.000000     607.000000
mean   303.000000  2021.407591  112297.869852
std    175.370085     0.690341   70957.259411
min      0.000000  2020.000000    2859.000000
25%    151.500000  2021.000000   62726.000000
50%    303.000000  2022.000000  101570.000000
75%    454.500000  2022.000000  150000.000000
max    606.000000  2022.000000  600000.000000

In [21]:
df3=pd.read_csv('Downloads/Data/Spotify_Youtube.csv', skiprows = 1, header = None,index_col=None)
display(df3.head())

,0,1,2,3,4,5,6,7,8,9
0,Artist,Track,Album,Album_type,Views,Likes,Comments,Licensed,official_video,Stream
1,Gorillaz,Feel Good Inc.,Demon Days,album,693555221.0,6220896.0,169907.0,True,True,1040234854.0
2,Gorillaz,Rhinestone Eyes,Plastic Beach,album,72011645.0,1079128.0,31003.0,True,True,310083733.0
3,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,8435055.0,282142.0,7399.0,True,True,63063467.0
4,Gorillaz,On Melancholy Hill,Plastic Beach,album,211754952.0,1788577.0,55229.0,True,True,434663559.0

In [25]:
df4=pd.read_csv('Downloads/Data/Spotify_Youtube.csv', skiprows = 2, header = 0,index_col = None)
display(df4.head())

,Artist,Track,Album,Album_type,Views,Likes,Comments,Licensed,official_video,Stream
0,Gorillaz,Feel Good Inc.,Demon Days,album,693555221.0,6220896.0,169907.0,True,True,1.040235e+09
1,Gorillaz,Rhinestone Eyes,Plastic Beach,album,72011645.0,1079128.0,31003.0,True,True,3.100837e+08
2,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,8435055.0,282142.0,7399.0,True,True,6.306347e+07
3,Gorillaz,On Melancholy Hill,Plastic Beach,album,211754952.0,1788577.0,55229.0,True,True,4.346636e+08
4,Gorillaz,Clint Eastwood,Gorillaz,album,618480958.0,6197318.0,155930.0,True,True,6.172597e+08